export const environment = {
  production: true,
  Modules: {
    account_payable: false,
    account_recievable: false,
    adt: true,
    ambulance: false,
    billing: true,
    biomedic_waste: false,
    cash_book: false,
    chiropractic: true,
    cssd: false,
    daycare: true,
    dental: true,
    dietkitchen: false,
    emergency: true,
    fixed_asset: false,
    general_ledger: false,
    house_keeping: false,
    inventory: false,
    ipd: false,
    lab: true,
    linen_laundry: false,
    master: true,
    mis_reports: true,
    mrd: false,
    ncp: true,
    opd: true,
    operation_theatre: true,
    pharmacy: false,
    procurement: false,
    queue_management: true,
    rehab: true,
    user_management: true,
    welfare: false
  },
  client_name: "dev"
};
