export const environment = {
  production: true,
  Modules: {
    account_payable: true,
    account_recievable: true,
    adt: true,
    ambulance: true,
    billing: true,
    biomedic_waste: true,
    cash_book: true,
    chiropractic: true,
    cssd: true,
    daycare: true,
    dental: true,
    dietkitchen: true,
    emergency: true,
    fixed_asset: false,
    general_ledger: true,
    house_keeping: true,
    inventory: true,
    ipd: false,
    lab: true,
    linen_laundry: false,
    master: true,
    mis_reports: true,
    mrd: true,
    ncp: true,
    opd: true,
    operation_theatre: true,
    pharmacy: true,
    procurement: true,
    queue_management: true,
    rehab: true,
    user_management: true,
    welfare: true
  },
  client_name: "dev"
};
