export const environment = {
  production: true,
  Modules: {
    account_payable: true,
    account_recievable: true,
    adt: false,
    ambulance: true,
    billing: false,
    biomedic_waste: true,
    cash_book: true,
    chiropractic: false,
    cssd: true,
    daycare: false,
    dental: false,
    dietkitchen: true,
    emergency: false,
    fixed_asset: true,
    general_ledger: true,
    house_keeping: true,
    inventory: true,
    ipd: false,
    lab: false,
    linen_laundry: true,
    master: false,
    mis_reports: false,
    mrd: true,
    ncp: false,
    opd: false,
    operation_theatre: false,
    pharmacy: true,
    procurement: true,
    queue_management: false,
    rehab: false,
    user_management: false,
    welfare: true
  },
  client_name: "dev"
};
