export const environment = {
  production: true,
  Modules: {
    account_payable: true,
    account_recievable: true,
    adt: false,
    ambulance: false,
    billing: true,
    biomedic_waste: false,
    cash_book: false,
    chiropractic: false,
    cssd: false,
    daycare: false,
    dental: false,
    dietkitchen: false,
    emergency: false,
    fixed_asset: false,
    general_ledger: true,
    house_keeping: false,
    inventory: true,
    ipd: false,
    lab: true,
    linen_laundry: false,
    master: true,
    mis_reports: true,
    mrd: false,
    ncp: false,
    opd: true,
    operation_theatre: true,
    pharmacy: true,
    procurement: true,
    queue_management: true,
    rehab: false,
    user_management: true,
    welfare: false
  },
  client_name: "rsd"
};
