export const environment = {
  production: true,
  Modules: {
    account_payable: false,
    account_recievable: false,
    adt: true,
    ambulance: false,
    billing: true,
    biomedic_waste: true,
    cash_book: false,
    chiropractic: false,
    cssd: true,
    daycare: false,
    dental: false,
    dietkitchen: false,
    emergency: true,
    fixed_asset: false,
    general_ledger: true,
    house_keeping: false,
    inventory: true,
    ipd: false,
    lab: true,
    linen_laundry: false,
    master: true,
    mis_reports: false,
    mrd: true,
    ncp: true,
    opd: true,
    operation_theatre: true,
    pharmacy: true,
    procurement: true,
    queue_management: true,
    rehab: false,
    user_management: true,
    welfare: true
  },
  client_name: "dev"
};
