export const MICROSERVICES = {
  ACCOUNT_PAYABLE: "/account-payable/",
  ACCOUNTING_MASTER_SERVICE: "/accountingmaster/",
  AUDIT_SERVICE: "/audit-service/",
  BIOMEDICWASTE_SERVICE: "/biomedicwaste-service/",
  CSSD_SERVICE: "/cssd-service/",
  GENERAL_LEDGER_SERVICE: "/general-ledger/",
  GRAPHQL_SERVICE: "/graphql-service/",
  ID_SERVICE: "/id-service/",
  INVENTORY_SERVICE: "/inventory-service/",
  IPD_SERVICE: "/ipd-service/",
  LAB_SERVICE: "/lab-service/",
  // MASTER_SERVICE: "/master-service/",
  MASTERS_SERVICE: "/masters-service/",
  MRD_SERVICE: "/mrd-service/",
  NOTIFICATION_SERVICE: "/notification-service/",
  NURSING_SERVICE: "/nursing-service/",
  OPD_SERVICE: "/opd-service/",
  OTIMS_SERVICE: "/otims-service/",
  PHARMACY_SERVICE: "/pharmacy-service/",
  REPORT_SERVICE: "/report-service/",
  RULE_ENGINE_SERVICE: "/rule-engine-service/",
  SCHEDULER_SERVICE: "/scheduler-service/",
  BILLING_SERVICE: "/sdgt-billing-service/"
};
